version: '3.8'

services:
  unifi-smarthub:
    build: .
    container_name: unifi-smarthub-production
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
