'use strict';

// 所有可供維運人員搜尋的狀態碼集中於此，避免散落 hardcode 字串。
const ERROR_CODES = Object.freeze({
    SYS_START: 'SYS-START-001',
    SYS_READY: 'SYS-READY-001',
    SYS_SHUTDOWN: 'SYS-SHUTDOWN-001',
    SYS_START_FAILED: 'SYS-START-FAILED-001',
    SYS_CONFIG_INVALID: 'SYS-CONFIG-001',
    SYS_UNCAUGHT_EXCEPTION: 'SYS-CRASH-001',
    SYS_UNHANDLED_REJECTION: 'SYS-CRASH-002',
    SYS_CPU_WARNING: 'SYS-CPU-001',
    SYS_CPU_CRITICAL: 'SYS-CPU-002',
    SYS_MEMORY_WARNING: 'SYS-MEM-001',
    SYS_MEMORY_CRITICAL: 'SYS-MEM-002',
    SYS_MEMORY_GROWTH: 'SYS-MEM-003',
    SYS_DISK_WARNING: 'SYS-DISK-001',
    SYS_DISK_CRITICAL: 'SYS-DISK-002',
    SYS_RESOURCE_RECOVERED: 'SYS-RESOURCE-OK-001',
    SYS_MONITOR_FAILED: 'SYS-MONITOR-001',

    DB_CONNECT_START: 'DB-CONN-001',
    DB_CONNECT_SUCCESS: 'DB-CONN-002',
    DB_CONNECT_FAILED: 'DB-CONN-003',
    DB_QUERY_FAILED: 'DB-QUERY-001',
    DB_QUERY_SLOW: 'DB-QUERY-SLOW-001',
    DB_TRANSACTION_FAILED: 'DB-TX-001',
    DB_HEALTH_FAILED: 'DB-HEALTH-001',
    DB_MIGRATION_START: 'DB-MIGRATE-001',
    DB_MIGRATION_SUCCESS: 'DB-MIGRATE-002',
    DB_MIGRATION_FAILED: 'DB-MIGRATE-003',
    DB_CLOSE: 'DB-CLOSE-001',

    API_REQUEST_START: 'API-REQ-001',
    API_REQUEST_COMPLETE: 'API-REQ-002',
    API_AUTH_FAILED: 'API-AUTH-001',
    API_VALIDATION_FAILED: 'API-VALID-001',
    API_NOT_FOUND: 'API-NOTFOUND-001',
    API_INTERNAL_ERROR: 'API-INTERNAL-001',
    API_HEALTH_OK: 'API-HEALTH-001',
    API_READY_OK: 'API-READY-001',
    API_NOT_READY: 'API-READY-002',

    WORKER_START: 'WORKER-START-001',
    WORKER_READY: 'WORKER-READY-001',
    WORKER_TASK_START: 'WORKER-TASK-001',
    WORKER_TASK_SUCCESS: 'WORKER-TASK-002',
    WORKER_TASK_FAILED: 'WORKER-TASK-003',
    WORKER_TASK_SKIPPED: 'WORKER-TASK-004',
    WORKER_STUCK: 'WORKER-STUCK-001',

    EXT_UNIFI_FAILED: 'EXT-UNIFI-001',
    EXT_NAS_FAILED: 'EXT-NAS-001',
    EXT_NAS_MONITOR_FAILED: 'EXT-NASMON-001',
    EXT_WIIM_FAILED: 'EXT-WIIM-001',
    EXT_UPS_FAILED: 'EXT-UPS-001',
    EXT_ADGUARD_FAILED: 'EXT-ADGUARD-001',
    EXT_LINUX_FAILED: 'EXT-LINUX-001',
    EXT_NOTIFICATION_FAILED: 'EXT-NOTIFY-001'
});

module.exports = { ERROR_CODES };
